package nrrrcdefinitions

var DlUltransmissionPeriodicityTdduldlpatternMap = map[DlUltransmissionPeriodicityTdduldlpattern]float64{
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS0P5:   0.5,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS0P625: 0.625,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS1:     1,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS1P25:  1.25,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS2:     2,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS2P5:   2.5,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS5:     5,
	DlUltransmissionPeriodicityTdduldlpattern_DL_ULTRANSMISSION_PERIODICITY_TDDULDLPATTERN_MS10:    10,
}
