package nrrrcdefinitions

var NrofPortsCsirsresourceMappingMap = map[NrofPortsCsirsresourceMapping]int{
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P1:  1,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P2:  2,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P4:  4,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P8:  8,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P12: 12,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P16: 16,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P24: 24,
	NrofPortsCsirsresourceMapping_NROF_PORTS_CSIRSRESOURCE_MAPPING_P32: 32,
}
